# Controls when the workflow will run
name: Test Suit

on:
  # Triggers the workflow on pull request events to the develop branch
  push:
    branches: [ main ]

jobs:
  test_job:
    name: Unit Test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest --continue

      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'

  android_test_job:
    name: Android Test

    env:
      GHP_USER: ${{ github.actor }}
      GHP_API_KEY: ${{ github.token }}

    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Start Emulator
        run: ./scripts/start_emulator.sh
        timeout-minutes: 20

      - name: Android Tests
        run: ./gradlew nebraska:debugExecuteScreenshotTests

      - name: Upload Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: android-test-records
          path: "**/build/reports"