name: Validate PR

on:
  # Triggers the workflow on pull request events to the main branch
  pull_request:
    branches: [ main ]

jobs:
  code_quality:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Runs a set of commands using the runners shell
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: "Run detekt"
        uses: alaegin/Detekt-Action@v1.18.1
        with:
          reviewdog_level: warning
          github_token: ${{ secrets.github_token }}
          detekt_config: config/detekt/detekt.yml
          reviewdog_filter: file
          detekt_excludes: "**/build/**,**/.idea/**,**/test/**,**/androidTest/**"
          reviewdog_reporter: github-pr-review

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter

  test_job:
    name: Unit Test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest --continue

      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'

  android_test_job:
    name: Android Test

    env:
      GHP_USER: ${{ github.actor }}
      GHP_API_KEY: ${{ github.token }}

    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck